######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 25 21:25:57 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
